EXTRA_VENDOR_LIBRARIES := \
    libhwbinder \
    libhidltransport \
    libqti_vndfwk_detect \
    vendor.display.config@1.0 \
    vendor.display.config@1.1 \
    vendor.display.config@1.2 \
    vendor.display.config@1.3 \
    vendor.display.config@1.4 \
    vendor.display.config@1.5 \
    vendor.display.config@1.6 \
    vendor.display.config@1.7 \
    vendor.display.config@1.8 \
    vendor.display.config@1.9 \
    vendor.qti.hardware.perf@1.0 \
    vendor.qti.hardware.perf@2.0 \
    vendor.qti.hardware.perf@2.1 \
    vendor.qti.hardware.btconfigstore@1.0 \
    vendor.qti.hardware.bluetooth_audio@2.0 \
    vendor.qti.hardware.camera.device@1.0 \
    android.hidl.allocator@1.0 \
    android.hidl.memory@1.0 \
    android.frameworks.displayservice@1.0 \
    android.frameworks.sensorservice@1.0 \
    android.hardware.audio@6.0 \
    android.hardware.audio.effect@6.0 \
    android.hardware.audio@6.0-util \
    android.hardware.audio.common@6.0 \
    android.hardware.audio.common@6.0-util \
    android.hardware.audio.common-util \
    android.hardware.biometrics.fingerprint@2.1 \
    android.hardware.bluetooth@1.0 \
    android.hardware.bluetooth.audio@2.0 \
    android.hardware.cas@1.0 \
    android.hardware.cas@1.1 \
    android.hardware.cas@1.2 \
    android.hardware.cas.native@1.0 \
    android.hardware.camera.common@1.0 \
    android.hardware.camera.device@1.0 \
    android.hardware.camera.device@3.2 \
    android.hardware.camera.device@3.3 \
    android.hardware.camera.device@3.4 \
    android.hardware.camera.device@3.5 \
    android.hardware.camera.provider@2.4 \
    android.hardware.drm@1.0 \
    android.hardware.drm@1.1 \
    android.hardware.drm@1.2 \
    android.hardware.drm@1.3 \
    android.hardware.drm@1.4 \
    android.hardware.health@1.0 \
    android.hardware.health@2.0 \
    android.hardware.health@2.1 \
    android.hardware.gnss@1.0 \
    android.hardware.gnss@1.1 \
    android.hardware.gnss@2.0 \
    android.hardware.gnss.visibility_control@1.0 \
    android.hardware.gnss.measurement_corrections@1.0 \
    android.hardware.graphics.composer@2.1 \
    android.hardware.graphics.composer@2.1-resources \
    android.hardware.power@1.0 \
    android.hardware.power@1.1 \
    android.hardware.power@1.2 \
    android.hardware.power.stats@1.0 \
    android.hardware.power-V1-ndk_platform \
    android.system.net.netd@1.1 \
    android.hardware.radio@1.0 \
    android.hardware.radio@1.1 \
    android.hardware.radio@1.2 \
    android.hardware.radio.config@1.0 \
    android.hardware.secure_element@1.0 \
    android.hardware.usb@1.0 \
    android.hardware.nfc@1.0 \
    android.hardware.vibrator@1.0 \
    android.hardware.keymaster@4.0 \
    android.hardware.keymaster@4.1 \
    android.hardware.gatekeeper@1.0 \
    android.hardware.light@2.0 \
    android.hardware.sensors@1.0 \
    android.hardware.soundtrigger@2.1 \
    android.hardware.soundtrigger@2.2 \
    android.hardware.tetheroffload.config@1.0 \
    android.hardware.tetheroffload.control@1.0 \
    android.hardware.wifi@1.5 \
    android.hardware.wifi.supplicant@1.4 \
    android.hardware.wifi.hostapd@1.3
